#
# Makefile for stand-alone compass input device drivers
#

obj-$(CONFIG_INV_YAS530) += inv-yas530.o
inv-yas530-objs += yas530_input.o

obj-$(CONFIG_INV_AK8975) += inv-ak8975.o
inv-ak8975-objs += ak8975_input.o

